fix: added ConsultingTypeService and refactored the ConsultingTypeSet…
virtualidentityag/diakonie-onlineBeratung-userService pull request #5
Opened 2021-05-03 15:56 UTC by Schweizer-Philipp

2021-05-12 08:17 UTC, daho4b requested changes

2021-05-12 08:17 UTC, daho4b commented on src/main/resources/application.properties
> +cache.consulting.type.configuration.timeToLiveSeconds=10800
I would suggest increasing the value for 'timeToLiveSeconds'

2021-05-12 08:17 UTC, daho4b commented on src/test/java/de/caritas/cob/userservice/api/service/ConsultingTypeServiceTest.java
> +  public void setup() {
Please name the test method speaking

2021-05-12 11:30 UTC, Schweizer-Philipp commented on src/main/java/de/caritas/cob/userservice/api/admin/service/ConsultingTypeAdminService.java
> +    //TODO
This class was removed in Feat/dob 61 remove consultingtype endpoint from admin api

2021-05-12 11:36 UTC, Schweizer-Philipp commented on src/main/java/de/caritas/cob/userservice/api/service/AskerImportService.java
> -    if (email != null && !email.equals(StringUtils.EMPTY)
email can't be null there, the IDE has noted that

2021-05-12 11:36 UTC, Schweizer-Philipp commented on src/main/java/de/caritas/cob/userservice/api/service/AskerImportService.java
> -    if (email != null && !email.equals(StringUtils.EMPTY)
email can't be null there, the IDE has noted that

2021-05-12 11:40 UTC, Schweizer-Philipp commented on src/test/java/de/caritas/cob/userservice/api/admin/service/ConsultingTypeAdminServiceIT.java
> +/*package de.caritas.cob.userservice.api.admin.service;
This class was removed in Feat/dob 61 remove consultingtype endpoint from admin api

2021-05-17 07:50 UTC, PepeCortisona approved these changes

2021-05-17 10:58 UTC, closed without merging